repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.4
  hooks:
    # Run the linter.
    - id: ruff-check
      files: ^be-livekit-py/
      types: [file, python]

    # Run the formatter.
    - id: ruff-format
      files: ^be-livekit-py/
      types: [file, python]