name: Lint LiveKit Python Backend

on:
  push:
    paths:
      - "be-livekit-py/**"
  pull_request:
    paths:
      - "be-livekit-py/**"

jobs:
  lint:
    name: 🛠️ Lint via Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "./be-livekit-py/.python-version"

      - name: Sync deps
        working-directory: be-livekit-py
        run: uv sync --locked --all-extras --dev

      - name: Ruff check
        working-directory: be-livekit-py
        run: uv run ruff check --output-format=github .

      - name: Type check
        working-directory: be-livekit-py
        run: uv run pyright
